apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolldice
spec:
  selector:
    matchLabels:
      app: rolldice
  template:
    metadata:
      labels:
        app: rolldice
    spec:
      containers:
      - name: rolldice
        image: dockerdaemon0901/rolldice:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        {{ if .Values.customconfig.enable }}  
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.customconfig.name }}
              key: OTEL_EXPORTER_OTLP_ENDPOINT
        {{ else }}
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.config.name }}
              key: OTEL_EXPORTER_OTLP_ENDPOINT
        {{ end }}