apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolldice
spec:
  selector:
    matchLabels:
      app: rolldice
  template:
    metadata:
      labels:
        app: rolldice
    spec:
      containers:
      - name: rolldice
        image: dockerdaemon0901/rolldice:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        envFrom:
        {{ if .Values.customconfig.enable }}
          - configMapRef:
              name: {{ .Values.customconfig.name }}
        {{ else }}
          - configMapRef:
              name: {{ .Values.config.name }}
        {{ end }}